name: Main
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Remove node_modules
        run: sudo rm -rf node_modules
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: ./
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --public dist
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}